"""
app/main.py
-----------
FastAPI application entry point.

This file:
    1. Creates the FastAPI app instance
    2. Registers CORS middleware (allows frontend to call the API)
    3. Registers all routers under /api/v1/
    4. Creates DB tables on startup
    5. Exposes a health check endpoint

RUN COMMAND (from backend/ folder with venv active):
    uvicorn app.main:app --reload

    --reload means the server restarts automatically when you save any file.

INTERACTIVE API DOCS (auto-generated by FastAPI):
    http://localhost:8000/docs     ← Swagger UI — test all endpoints
    http://localhost:8000/redoc   ← ReDoc — cleaner read-only docs
"""

from contextlib import asynccontextmanager

from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware

from app.api.v1 import ai, analytics, assessments, auth, courses
from app.core.config import get_settings
from app.core.logging import get_logger, setup_logging

# IMPORTANT: Import ALL models before create_tables() is called.
# SQLAlchemy needs to see the model classes to know what tables to create.
from app.models import analytics as analytics_models  # noqa: F401
from app.models import assessment as assessment_models  # noqa: F401
from app.models import course as course_models  # noqa: F401
from app.models import user as user_models  # noqa: F401
from app.db.session import create_tables

settings = get_settings()
setup_logging(debug=settings.debug)
logger = get_logger(__name__)


# ── Lifespan ───────────────────────────────────────────────────────────────
# Lifespan replaces the old @app.on_event("startup") pattern.
# Code before yield runs on startup, code after yield runs on shutdown.

@asynccontextmanager
async def lifespan(app: FastAPI):
    """Application startup and shutdown logic."""
    # ── Startup ──
    logger.info("Starting %s...", settings.app_name)
    await create_tables()
    logger.info("Database tables created/verified.")
    logger.info("API docs available at: http://localhost:8000/docs")
    logger.info("Server ready.")

    yield  # ← app runs here

    # ── Shutdown ──
    logger.info("Shutting down %s.", settings.app_name)


# ── App instance ───────────────────────────────────────────────────────────

app = FastAPI(
    title=settings.app_name,
    description="AI-Powered Multi-Modal Learning Platform API",
    version="1.0.0",
    docs_url="/docs",
    redoc_url="/redoc",
    lifespan=lifespan,
)


# ── CORS Middleware ────────────────────────────────────────────────────────
# CORS (Cross-Origin Resource Sharing) allows the React frontend
# running on http://localhost:5173 to call this API on port 8000.
# Without this, the browser blocks all API calls from the frontend.

app.add_middleware(
    CORSMiddleware,
    allow_origins=[
        settings.frontend_url,          # http://localhost:5173 (from .env)
        "http://localhost:3000",         # fallback if Vite uses port 3000
        "http://127.0.0.1:5173",        # alternative localhost form
    ],
    allow_credentials=True,             # needed for Authorization header
    allow_methods=["*"],                # GET, POST, PUT, DELETE, OPTIONS
    allow_headers=["*"],                # Authorization, Content-Type, etc.
)


# ── Routers ────────────────────────────────────────────────────────────────
# All routes are prefixed with /api/v1/
# Example: POST /api/v1/auth/login

API_PREFIX = "/api/v1"

app.include_router(auth.router,        prefix=API_PREFIX)
app.include_router(courses.router,     prefix=API_PREFIX)
app.include_router(ai.router,          prefix=API_PREFIX)
app.include_router(assessments.router, prefix=API_PREFIX)
app.include_router(analytics.router,   prefix=API_PREFIX)


# ── Health check ───────────────────────────────────────────────────────────

@app.get("/health", tags=["Health"])
async def health_check():
    """
    Simple health check endpoint.
    Returns 200 if the server is running.
    Used to verify the server started correctly.
    """
    return {
        "status": "healthy",
        "app": settings.app_name,
        "version": "1.0.0",
    }


@app.get("/", tags=["Health"])
async def root():
    """Root endpoint — redirects to API docs."""
    return {
        "message": f"Welcome to {settings.app_name} API",
        "docs": "http://localhost:8000/docs",
        "health": "http://localhost:8000/health",
    }